### ISSUE TITLE
Do you have any plans to add other types of transform

### ISSUE THREAD

**Issue by gabrielfougeron** [IntelPython/mkl_fft#85]
Hi,

I've been using mkl_fft as a backend for scipy for a while now, and it works great!
Unless i'm mistaken, the available 1-D transforms are the fft and rfft.
Do you have any plan to add dct and dst?

**Comment by oleksandr-pavlyk** [comment]
Thank you for the question. `mkl_fft` provides wrappers for what is available in MKL. Since MKL itself does not provide API for DCT and DST, `mkl_fft` can only provide implementations that leverage `rfft` on a suitably modified input, in the spirit of https://ieeexplore.ieee.org/document/1163351 

It remains to be seen whether such an approach brings the acceleration over `scipy.fft.dct` and ``scipy.fft.dst`.

**Comment by gabrielfougeron** [comment]
Thank you very much for getting back to me so fast.
I did not know MKL did not provide and API for the dct and dst, thanks for clearing that up.

I've run a small benchmark to assess whether there could be an advantage. It compares timings of different fft implementations.  The "size" parameter is scaled by 1 for the fft, 2 for the rfft, 4 for the dct I and dst I, and 8 for the dst III and dct III (size of an equivalent non symmetric input).

It seems to me rfft is still competitive compared to scipy and pyfftw (using plan 'FFTW_MEASURE').

Of course this does not account for the necessary copies to create the modified input.

![sphx_glr_FFT_bench_001](https://github.com/IntelPython/mkl_fft/assets/8499652/571294df-2540-448d-ae3e-31f916702466)

**Comment by gabrielfougeron** [comment]
Oh wait, I think I wrote my previous answer too quickly. Your article (actually rather the abstract of your article. I don't have access to the full article) suggests that the factor of 2 I assumed can be reduced to 1 with careful re-ordering. This is very interesting and completely defeats my preconceived idea.
